### ISSUE TITLE
self-enclosed tags incorrectly end up as child tags after parsing

### ISSUE THREAD

**Issue by SuhaybMahmood** [nolanw/HTMLReader#34]
We found that self-enclosed tags end up as child tags after loading the html into an `HTMLDocument*` then retrieving using either `innerHTML` or `serializedFragment` methods:

```
NSString* rawHtmlString = @"<html><body><div class=\"self-enclosed\"/><div class=\"also-self-enclosed\"/></body></html>";
HTMLDocument *document = [HTMLDocument documentWithString:rawHtmlString];
NSString* formattedHtmlString= [document innerHTML];
NSLog(@"rawHtmlString: %@", rawHtmlString);
NSLog(@"formattedHtmlString: %@", formattedHtmlString);
```
Log:
2015-08-04 10:25:56.976 App[2819:40244] rawHtmlString: &lt;html&gt;&lt;body&gt;&lt;div class=&quot;self-enclosed&quot;/&gt;&lt;div class=&quot;also-self-enclosed&quot;/&gt;&lt;/body&gt;&lt;/html&gt;
2015-08-04 10:25:59.343 App[2819:40244] formattedHtmlString: &lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;div class=&quot;self-enclosed&quot;&gt;&lt;div class=&quot;also-self-enclosed&quot;&gt;&lt;/div&gt;&lt;/div&gt;&lt;/body&gt;&lt;/html&gt;

are we doing something wrong or does the parser have an issue processing self-enclosed tags?

**Comment by nolanw** [comment]
I believe the markup in `rawHtmlString` is being parsed correctly. `div` tags are not treated as self-closing tags according to the spec, so that markup is parsed as if you had written:
```html
<html><body><div class="self-enclosed"><div class="also-self-enclosed"></body></html>
```
I can't really speak to who's to blame for the situation, but that's the situation you are in.

If you're curious, [here's the big list of what happens](https://html.spec.whatwg.org/multipage/syntax.html#parsing-main-inbody) when the parser comes across an element in the `<body>`. If you look at a tag that is treated as self-closing, like `<img>`, one of the steps on that page is to "Acknowledge the token's self-closing flag, if it is set." That step is absent from the handling of `<div>`.

(Fun fact: it's actually a parse error to try to make a `<div>` self-closing, but HTMLReader doesn't bother exposing parse errors, so there's not really any way for you to have known that!)

**Comment by SuhaybMahmood** [comment]
I used div in the example only for demonstration purposes; that's not actually whats causing our problem (looks like using divs for demonstration was a bad choice in hindsight :P). The tags we're seeing this happen on are custom ones we get from our server which we use this library to identify and process, would these be treated with the same rules as for divs? ie:
```
NSString *rawHtmlString = @"<html><body><customTag class=\"self-enclosed\"/><customTag class=\"also-self-enclosed\"/></body></html>";
HTMLDocument *document = [HTMLDocument documentWithString:rawHtmlString];
NSString* formattedHtmlString= [document innerHTML ];
NSLog(@"rawHtmlString: %@", rawHtmlString);
NSLog(@"formattedHtmlString: %@", formattedHtmlString);
```
Log:
2015-08-05 10:20:30.775 App[3962:28154] rawHtmlString: &lt;html&gt;&lt;body&gt;&lt;customTag class=&quot;self-enclosed&quot;/&gt;&lt;customTag class=&quot;also-self-enclosed&quot;/&gt;&lt;/body&gt;&lt;/html&gt;
2015-08-05 10:20:33.886 App[3962:28154] formattedHtmlString: &lt;html&gt;&lt;head&gt;&lt;/head&gt;&lt;body&gt;&lt;customtag class=&quot;self-enclosed&quot;&gt;&lt;customtag class=&quot;also-self-enclosed&quot;&gt;&lt;/customtag&gt;&lt;/customtag&gt;&lt;/body&gt;&lt;/html&gt;

**Comment by nolanw** [comment]
They are indeed treated the same in that they are never considered self-closing.

If you have control over the output, maybe you can insert closing tags? Or you might have better luck using an XML parser.

**Comment by SuhaybMahmood** [comment]
Ah in that case sounds like this might not be a bug. We have already done a workaround where we find our self enclosing tags and add closing tags but thought we were working around a bug; hence raising the issue. We'll continue with that. Thank you for taking the time to get back to us, it is much appreciated :)

**Comment by nolanw** [comment]
Happy to help!
