### ISSUE TITLE
Is there a way to grab the text in an element?

### ISSUE THREAD

**Issue by mrahmiao** [nolanw/HTMLReader#43]
When I traversed the DOM tree using `treeEnumerator` of `HTMLNode`, I can see the text node: `HTMLTextNode`. However, it is not exposed as a public API so that I can't type cast to it.

And the `textContent` of `HTMLNode` includes too many text, which is useless.

I have a HTML file which contains the following code:

    <dd>
      Some Description
      <dl>...</dl>
    </dd>

**Comment by nolanw** [comment]
Hello! Excellent point. I think we should do two things:

1. Expose `HTMLTextNode` publicly, at least enough of an interface to make it usable when using `treeEnumerator`.
2. Add a `textContentComponents` property to `HTMLNode` that returns an array of each child text node's contents, so that you can get what you need without having to know anything about `HTMLTextNode`.

Make sense?

**Comment by mrahmiao** [comment]
Make `HTMLTextNode` as a public API is enough

**Comment by nolanw** [comment]
@mrahmiao Shipped in version 0.9.2!
